name: Release Creation
description: Compresses images and creates zip artifact for release

inputs:
  tag_name: 
    description: 'The release tag'
    required: false
    type: string

  src_directory: 
    description: 'The release directory'
    required: false
    type: string
    default: 'src'

runs:
  using: "composite"
  steps:
   - name: Install LibVips
     run: |
       time ( \
         sudo apt update; \
         sudo apt install libvips-tools rename libjpeg-turbo8; \
      )
     shell: bash

   - name: Resize images to optimized thumbnails
     run: |
       time ( \
         find ./${{inputs.src_directory}}/* -name '*.jpeg' -size +100k | parallel vipsthumbnail "{}" --size 650x1300 --export-profile srgb -o tn_%s.jpeg[Q=70,profile=none,strip=true]; \
         find ./${{inputs.src_directory}}/* -name '*.jpg' -size +100k | parallel vipsthumbnail "{}" --size 650x1300 --export-profile srgb -o tn_%s.jpg[Q=70,profile=none,strip=true]; \
         find ./${{inputs.src_directory}}/* -name '*.png' -size +100k | parallel vipsthumbnail "{}" --size 650x1300 --export-profile srgb -o tn_%s.png[Q=70,profile=none,strip=true,compression=0]; \
         find ./${{inputs.src_directory}}/* -name '*.gif' -size +100k | parallel vipsthumbnail "{}" --size 650x1300 --export-profile srgb -o tn_%s.gif[strip=true]; \
       )
     shell: bash

   - name: Replace images with their thumbnails
     run: |
       time find ./${{inputs.src_directory}}/* -type f -name tn_* -exec rename -f -d 's/tn_//' {} \;
     shell: bash

   # This is step was added due to git not supporting capitalization control
   - name: Rename all directories and files to lowercase
     run: |
       time ( \
         find ./${{inputs.src_directory}}/* -depth -regex ".*[A-Z]+.*" -type d -exec rename -d 'y/A-Z/a-z/' {} \;; \
         find ./${{inputs.src_directory}}/* -depth -regex ".*[A-Z]+.*" -type f -exec rename -d 'y/A-Z/a-z/' {} \;; \
       )
     shell: bash  

    # For zip -r to do what we want, it is necessary to change directory first
   - name: Create release zip
     run: |
       cd ./${{inputs.src_directory}}
       zip -r protocol.zip .
     shell: bash

   - name: Upload release ZIP
     uses: softprops/action-gh-release@v2
     with:
        files: ./${{inputs.src_directory}}/protocol.zip
        tag_name: ${{ inputs.tag_name }}
