name: Release Creation
description: Compresses images and creates zip artifact for release

inputs:
  tag_name: 
    description: 'The release tag we upload to'
    required: false
    type: string

  src_directory: 
    description: 'The directory to zip attached to release'
    required: false
    type: string
    default: 'src'

runs:
  using: "composite"
  steps:
   - name: checkout
     uses: actions/checkout@v4

   - name: Install ImageMagick
     uses: mfinelli/setup-imagemagick@v6

   - name: Resize all images using default names
     run: find . -type f -regextype posix-egrep -regex ".+\.(gif|bmp|png|jpg|jpeg)$" -size +100k | parallel magick mogrify -define jpeg:size=650x1300 png:compression-level=0 -geometry 650x1300 -quality 70 "{}"
     shell: bash

   - name: Create release zip
     run: |
       cd ./${{inputs.src_directory}}
       zip -r protocol.zip .
     shell: bash

   - name: Upload release ZIP
     uses: softprops/action-gh-release@v2
     with:
        files: ./${{inputs.src_directory}}/protocol.zip
        tag_name: ${{ inputs.tag_name }}
