name: Release Creation
description: Compresses images and creates zip artifact for release

inputs:
  tag_name: 
    description: 'The release tag'
    required: false
    type: string

  src_directory: 
    description: 'The release directory'
    required: false
    type: string
    default: 'src'

runs:
  using: "composite"
  steps:
   - name: checkout
     uses: actions/checkout@v4

   - name: Install LibVips
     run: |
       sudo apt update
       sudo apt install libvips-tools rename libjpeg-turbo8
     shell: bash

   - name: Resize images to optimized thumbnails
     run: |
       cd ./${{inputs.src_directory}}
       find -name '*.jpeg' -size +100k | parallel vipsthumbnail "{}" --size 650x1300 --export-profile srgb -o tn_%s.jpeg[Q=70,profile=none,strip=true]
       find -name '*.jpg' -size +100k | parallel vipsthumbnail "{}" --size 650x1300 --export-profile srgb -o tn_%s.jpg[Q=70,profile=none,strip=true]
       find -name '*.png' -size +100k | parallel vipsthumbnail "{}" --size 650x1300 --export-profile srgb -o tn_%s.png[Q=70,profile=none,strip=true,compression=0]
       find -name '*.gif' -size +100k | parallel vipsthumbnail "{}" --size 650x1300 --export-profile srgb -o tn_%s.gif[strip=true]
       find . -type f -name tn_* -exec rename -f -d 's/tn_//' {} \;
     shell: bash

   - name: Replace images with their thumbnails
     run: |
       cd ./${{inputs.src_directory}}
       find . -type f -name tn_* -exec rename -f -d 's/tn_//' {} \;
     shell: bash

# This conflicts with Selection Flows but is necessary due to git's handling of capitalization
# making it impossible for protocol creators to truly control the capitalization of their files.
   - name: Rename all directories and files to lowercase
     run: |
       find ./${{inputs.src_directory}} -depth -regex ".*[A-Z]+.*" -type d -exec rename -d 'y/A-Z/a-z/' {} \;
       find ./${{inputs.src_directory}} -depth -regex ".*[A-Z]+.*" -type f -exec rename -d 'y/A-Z/a-z/' {} \;
     shell: bash  

   - name: Create release zip
     run: |
       cd ./${{inputs.src_directory}}
       zip -r protocol.zip .
     shell: bash

   - name: Upload release ZIP
     uses: softprops/action-gh-release@v2
     with:
        files: ./${{inputs.src_directory}}/protocol.zip
        tag_name: ${{ inputs.tag_name }}
